apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: customer-support-agent-service
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
      # This points to the image Artifact Registry path built by Cloud Build
      - image: us-west1-docker.pkg.dev/gci-techss-gcp-pjnp-01nl165115/agent-repository/customer-support-agent:latest
        resources:
          limits:
            cpu: "1"
            memory: 512Mi